#!/usr/bin/env python3
"""Write pins.txt from make_notebooks.META - on the laptop, never on the pod.

The first paper run shipped pins as a text file the pod read with grep. A
refactor moved the computation onto the pod, where it imported the whole
package under the base image's Python before any venv existed, and every
model failed with an empty pip line. This is the old pattern back: the
generator is the single source of truth, the file is what travels, and a
test fails if they drift.

    python scripts/runpod/pins.py --write      # regenerate pins.txt
    python scripts/runpod/pins.py <key>        # print one model's pins
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PINS_TXT = os.path.join(HERE, "pins.txt")


def generate() -> dict[str, str]:
    sys.path.insert(0, os.path.join(HERE, ".."))
    sys.path.insert(0, os.path.join(HERE, "..", ".."))
    import make_notebooks as mk  # noqa: E402
    from undertone import adapters  # noqa: E402

    out = {}
    for key in adapters.list_adapters() + adapters.list_controls():
        pins = list(mk.META.get(key, {}).get("pip", mk.BASE_PIP))
        if key.startswith("cascaded_"):
            # Mirrors build_cascaded_notebook: the control adds the ASR engine.
            pins.append("faster-whisper>=1.0.0")
        out[key] = " ".join(pins)
    return out


def render(pins: dict[str, str]) -> str:
    return ("# key|pip requirements. Generated by `python scripts/runpod/pins.py --write`;\n"
            "# a test fails if this drifts from make_notebooks.META. Read on the pod with\n"
            "# grep so no Python runs there before the venv exists.\n"
            + "".join(f"{k}|{v}\n" for k, v in pins.items()))


if __name__ == "__main__":
    if sys.argv[1:] == ["--write"]:
        open(PINS_TXT, "w").write(render(generate()))
        print(f"wrote {PINS_TXT}")
    else:
        print(generate()[sys.argv[1]])
